# Retrieval Query Strategy Comparison (Qdrant)

This notebook evaluates three retrieval query strategies over 10 random samples from `evaluation.json` using Qdrant at `localhost:6333`.

Strategies:
- Regex/string-based (helper functions) intelligent query generation.

In [ ]:
import json
import random
import re
from pathlib import Path


import pandas as pd
from sentence_transformers import SentenceTransformer
from qdrant_client import QdrantClient
from qdrant_client import models

RANDOM_SEED = 42
SAMPLE_SIZE = 10
TOP_K = 10
COLLECTION_NAME = "guideline_embeddings"
MODEL_NAME = "BAAI/bge-large-en-v1.5"

PROJECT_ROOT = Path("..").resolve()
DATA_DIR = PROJECT_ROOT / "data" / "processed"
EVAL_PATH = DATA_DIR / "evaluation.json"
EVAL_FILES_DIR = DATA_DIR / "evaluation_files"

print(f"Project root: {PROJECT_ROOT}")
print(f"Evaluation file: {EVAL_PATH}")

c:\Users\budhi\Documents\IITM\DSAI Lab\Group-1-DS-and-AI-Lab-Project\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Project root: C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1-DS-and-AI-Lab-Project
Evaluation file: C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1-DS-and-AI-Lab-Project\data\processed\evaluation.json

In [9]:
import sys
sys.path.insert(0, str(PROJECT_ROOT / "src"))
from data_processing.indent_signal import check_indent_errors

In [2]:
# Load evaluation data and select 10 random samples
with EVAL_PATH.open("r", encoding="utf-8") as f:
    evaluation_data = json.load(f)

random.seed(RANDOM_SEED)
sampled_entries = random.sample(evaluation_data, k=min(SAMPLE_SIZE, len(evaluation_data)))

def resolve_source_file(entry):
    source_path = Path(entry["source_file"])
    if source_path.is_absolute():
        return source_path
    return EVAL_FILES_DIR / source_path.name if not (EVAL_FILES_DIR / source_path).exists() else EVAL_FILES_DIR / source_path

for entry in sampled_entries:
    file_path = resolve_source_file(entry)
    entry["resolved_source_file"] = str(file_path)
    entry["file_text"] = file_path.read_text(encoding="utf-8", errors="ignore")

print(f"Loaded {len(evaluation_data)} total entries")
print(f"Sampled {len(sampled_entries)} entries")
pd.DataFrame([
    {
        "id": e["id"],
        "repo": e["repo"],
        "source_path": e["source_path"],
        "resolved_source_file": e["resolved_source_file"]
    }
    for e in sampled_entries
])

Loaded 97 total entries
Sampled 10 entries

,id,repo,source_path,resolved_source_file
0,synthetic-sklearn_PR_24,kannan-dedsec/synthetic-sklearn,custom_transformer.py,C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1...
1,synthetic-django_PR_36,kannan-dedsec/synthetic-django,urls.py,C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1...
2,synthetic-django_PR_24,kannan-dedsec/synthetic-django,managers.py,C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1...
3,synthetic-sklearn_PR_38,kannan-dedsec/synthetic-sklearn,tests/test_models.py,C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1...
4,synthetic-fastapi_PR_38,kannan-dedsec/synthetic-fastapi,tests/test_users.py,C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1...
5,synthetic-fastapi_PR_34,kannan-dedsec/synthetic-fastapi,schemas/item.py,C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1...
6,synthetic-fastapi_PR_31,kannan-dedsec/synthetic-fastapi,routers/auth.py,C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1...
7,synthetic-django_PR_39,kannan-dedsec/synthetic-django,views.py,C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1...
8,synthetic-django_PR_35,kannan-dedsec/synthetic-django,tests/test_views.py,C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1...
9,synthetic-sklearn_PR_30,kannan-dedsec/synthetic-sklearn,hyperparameter_tuning.py,C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1...

In [3]:
# Connect to Qdrant and load embedding model
client = QdrantClient(url="http://localhost:6333")
collection_info = client.get_collection(COLLECTION_NAME)
print(f"Connected to Qdrant. Collection: {COLLECTION_NAME}")
print(f"Points count: {collection_info.points_count}")

model = SentenceTransformer(MODEL_NAME)
print(f"Loaded model: {MODEL_NAME}")

Connected to Qdrant. Collection: guideline_embeddings
Points count: 505

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 391/391 [00:00<00:00, 2681.83it/s]
BertModel LOAD REPORT from: BAAI/bge-large-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loaded model: BAAI/bge-large-en-v1.5

In [4]:
COMMON_SOURCE_TYPES = ["pep8", "flake8", "pylint", "ruff"]

def repo_family(repo_name):
    repo_lower = repo_name.lower()
    for family in ["django", "fastapi", "flask", "pandas", "sklearn", "scikit-learn"]:
        if family in repo_lower:
            return "scikit-learn" if family == "sklearn" else family
    return None

def build_query_filter(repo_name):
    family = repo_family(repo_name)
    should_conditions = [
        models.FieldCondition(key="source_type", match=models.MatchValue(value=s))
        for s in COMMON_SOURCE_TYPES
    ]
    if family:
        should_conditions.insert(
            0,
            models.FieldCondition(
                key="source_type",
                match=models.MatchValue(value=f"{family}_guidelines"),
            ),
        )
        should_conditions.insert(
            1,
            models.FieldCondition(
                key="source_type",
                match=models.MatchValue(value=f"{family}_review_comment"),
            ),
        )
    return models.Filter(should=should_conditions)

def retrieve_guidelines(query_text, repo_name, top_k=TOP_K):
    query_vector = model.encode(query_text).tolist()
    response = client.query_points(
        collection_name=COLLECTION_NAME,
        query=query_vector,
        query_filter=build_query_filter(repo_name),
        limit=top_k,
    )
    return response.points

print("Retrieval helpers ready")

Retrieval helpers ready

In [10]:
# Strategy 2: Regex/string-based intelligent query
def query_strategy_regex_intelligent(entry):
    text = entry["file_text"]
    lines = text.splitlines()

    imports = [ln.strip() for ln in lines if re.match(r"^\s*(import|from)\s+", ln)]
    camel_case_identifiers = set(re.findall(r"\b[a-z]+[A-Z][A-Za-z0-9_]*\b", text))
    mutable_defaults = re.findall(r"def\s+\w+\([^)]*=\s*(\[\]|\{\}|dict\(|list\()", text)

    # Use the check_indent_errors function from indent_signal.py
    indent_issues = check_indent_errors(entry["resolved_source_file"])

    docstring_markers = len(re.findall(r"'''|\"\"\"", text))

    signals = [
        f"repo family: {repo_family(entry['repo'])}",
        f"import statements count: {len(imports)}",
        f"camelCase identifiers: {', '.join(sorted(list(camel_case_identifiers))[:8]) or 'none'}",
        f"mutable-default patterns: {len(mutable_defaults)}",
        f"indentation issues: {len(indent_issues)}",
        f"docstring markers count: {docstring_markers}",
        "focus on naming_convention, unused_import, indentation, mutable_default, documentation_formatting"
    ]

    return " ; ".join(signals)

print("Strategy 2 query builders ready")

Strategy 2 query builders ready

In [11]:
# Run strategy 2 over sampled entries and collect retrieved chunks with timing
import time

chunk_rows = []
for entry in sampled_entries:
    try:
        query_text = query_strategy_regex_intelligent(entry)
    except Exception as e:
        query_text = f"<error building query: {e}>"

    start = time.perf_counter()
    try:
        points = retrieve_guidelines(query_text, entry.get('repo', ''), top_k=TOP_K)
    except Exception as e:
        points = []
    end = time.perf_counter()

    retrieval_time = end - start

    # Safely extract payload representations for storage
    payloads = []
    for p in points:
        try:
            payload = getattr(p, 'payload', p)
        except Exception:
            payload = p
        payloads.append(str(payload))

    if payloads:
        per_chunk_time = retrieval_time / max(1, len(payloads))
        for idx, payload in enumerate(payloads):
            chunk_rows.append({
                'id': entry.get('id'),
                'repo': entry.get('repo'),
                'source_path': entry.get('source_path'),
                'resolved_source_file': entry.get('resolved_source_file'),
                'query': query_text,
                'retrieved_count': len(payloads),
                'chunk_index': idx,
                'retrieved_payload': payload,
                'retrieval_time': retrieval_time,
                'time_taken': per_chunk_time,
            })
    else:
        # No points returned; record a single row with empty payload and the retrieval time
        chunk_rows.append({
            'id': entry.get('id'),
            'repo': entry.get('repo'),
            'source_path': entry.get('source_path'),
            'resolved_source_file': entry.get('resolved_source_file'),
            'query': query_text,
            'retrieved_count': 0,
            'chunk_index': None,
            'retrieved_payload': None,
            'retrieval_time': retrieval_time,
            'time_taken': retrieval_time,
        })

results_df = pd.DataFrame(chunk_rows)
results_df.head()

,id,repo,source_path,resolved_source_file,query,retrieved_count,chunk_index,retrieved_payload,retrieval_time,time_taken
0,synthetic-sklearn_PR_24,kannan-dedsec/synthetic-sklearn,custom_transformer.py,C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1...,repo family: scikit-learn ; import statements ...,10,0,{'text': 'N813: CamelCase imported as lowercas...,7.629858,0.762986
1,synthetic-sklearn_PR_24,kannan-dedsec/synthetic-sklearn,custom_transformer.py,C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1...,repo family: scikit-learn ; import statements ...,10,1,{'text': 'N817: CamelCase imported as acronym....,7.629858,0.762986
2,synthetic-sklearn_PR_24,kannan-dedsec/synthetic-sklearn,custom_transformer.py,C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1...,repo family: scikit-learn ; import statements ...,10,2,{'text': 'N814: CamelCase imported as constant...,7.629858,0.762986
3,synthetic-sklearn_PR_24,kannan-dedsec/synthetic-sklearn,custom_transformer.py,C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1...,repo family: scikit-learn ; import statements ...,10,3,"{'text': 'Python packages should have short, a...",7.629858,0.762986
4,synthetic-sklearn_PR_24,kannan-dedsec/synthetic-sklearn,custom_transformer.py,C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1...,repo family: scikit-learn ; import statements ...,10,4,{'text': 'W0404 (reimported): A module is impo...,7.629858,0.762986

In [24]:
# Aggregate results by PR and show ground-truth violations with retrieved chunks
# Load ground_truth_reviews directly from evaluation.json
with open(EVAL_PATH, 'r', encoding='utf-8') as f:
    full_eval = json.load(f)

print(f"Loaded full evaluation data for ground truth mapping: {len(full_eval)} entries")
for i in range(3):
    print(f"Sample entry {i}: ID={full_eval[i].get('id')}, GT Violations={full_eval[i].get('ground_truth_reviews')}")
gt_map = {e.get('id'): e.get('ground_truth_reviews') for e in full_eval}

Loaded full evaluation data for ground truth mapping: 97 entries
Sample entry 0: ID=synthetic-django_PR_21, GT Violations=[{'line_number': 9, 'violation_category': 'unused_import', 'review_comment': 'Unused import: os'}, {'line_number': 10, 'violation_category': 'unused_import', 'review_comment': 'Unused import: sys'}, {'line_number': 11, 'violation_category': 'unused_import', 'review_comment': 'Unused import: re'}]
Sample entry 1: ID=synthetic-django_PR_22, GT Violations=[{'line_number': 43, 'violation_category': 'naming_convention', 'review_comment': 'camelCase function name: cleanTitle'}, {'line_number': 76, 'violation_category': 'naming_convention', 'review_comment': 'camelCase function name: cleanName'}]
Sample entry 2: ID=synthetic-django_PR_23, GT Violations=[{'line_number': 11, 'violation_category': 'unused_import', 'review_comment': 'Unused import: os'}, {'line_number': 12, 'violation_category': 'unused_import', 'review_comment': 'Unused import: sys'}, {'line_number': 13, 'violation_category': 'unused_import', 'review_comment': 'Unused import: re'}, {'line_number': 24, 'violation_category': 'indentation', 'review_comment': 'Non-4-space indent (2 spaces)'}, {'line_number': 34, 'violation_category': 'indentation', 'review_comment': 'Non-4-space indent (6 spaces)'}, {'line_number': 60, 'violation_category': 'indentation', 'review_comment': 'Non-4-space indent (6 spaces)'}, {'line_number': 34, 'violation_category': 'documentation_formatting', 'review_comment': "Docstring indentation doesn't match block"}, {'line_number': 36, 'violation_category': 'documentation_formatting', 'review_comment': "Docstring indentation doesn't match block"}, {'line_number': 60, 'violation_category': 'documentation_formatting', 'review_comment': "Docstring indentation doesn't match block"}, {'line_number': 62, 'violation_category': 'documentation_formatting', 'review_comment': "Docstring indentation doesn't match block"}]

In [27]:
# temp save for results_df.to_csv("retrieval_strategy_2_results.csv", index=False)
results_df.to_csv("retrieval_strategy_2_results.csv", index=False)

In [25]:
gt_map

{'synthetic-django_PR_21': [{'line_number': 9,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: os'},
  {'line_number': 10,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: sys'},
  {'line_number': 11,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: re'}],
 'synthetic-django_PR_22': [{'line_number': 43,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: cleanTitle'},
  {'line_number': 76,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: cleanName'}],
 'synthetic-django_PR_23': [{'line_number': 11,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: os'},
  {'line_number': 12,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: sys'},
  {'line_number': 13,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: re'},
  {'line_number': 24,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (2 spaces)'},
  {'line_number': 34,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (6 spaces)'},
  {'line_number': 60,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (6 spaces)'},
  {'line_number': 34,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 36,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 60,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 62,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"}],
 'synthetic-django_PR_24': [{'line_number': 32,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: byAuthor'},
  {'line_number': 42,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: withinDateRange'},
  {'line_number': 83,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: byAuthor'},
  {'line_number': 93,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: withinDateRange'},
  {'line_number': 32,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default [] for param 'author_id'"},
  {'line_number': 42,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default [] for param 'start_date'"},
  {'line_number': 42,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default {} for param 'end_date'"},
  {'line_number': 83,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default [] for param 'author_id'"},
  {'line_number': 93,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default [] for param 'start_date'"},
  {'line_number': 93,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default {} for param 'end_date'"}],
 'synthetic-django_PR_25': [{'line_number': 16,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: os'},
  {'line_number': 17,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: sys'},
  {'line_number': 18,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: re'}],
 'synthetic-django_PR_26': [{'line_number': 27,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: getAbsoluteUrl'},
  {'line_number': 79,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: getAbsoluteUrl'},
  {'line_number': 10,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (2 spaces)'},
  {'line_number': 53,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (6 spaces)'},
  {'line_number': 10,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 12,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 53,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 55,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"}],
 'synthetic-django_PR_28': [{'line_number': 8,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: os'},
  {'line_number': 9,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: sys'},
  {'line_number': 10,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: re'},
  {'line_number': 29,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default [] for param 'value'"},
  {'line_number': 52,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default {} for param 'value'"},
  {'line_number': 62,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default {} for param 'attrs'"}],
 'synthetic-django_PR_29': [{'line_number': 9,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: os'},
  {'line_number': 10,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: sys'},
  {'line_number': 11,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: re'},
  {'line_number': 19,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase variable: secretKey'},
  {'line_number': 21,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase variable: allowedHosts'},
  {'line_number': 57,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase variable: authPasswordValidators'}],
 'synthetic-django_PR_30': [{'line_number': 24,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: generateArticleSlug'},
  {'line_number': 24,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase parameter: extraArgs'},
  {'line_number': 41,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: cleanupRelatedResources'},
  {'line_number': 49,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: handleArticleTagsChange'},
  {'line_number': 24,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default [] for param 'sender'"},
  {'line_number': 41,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default {} for param 'sender'"}],
 'synthetic-django_PR_31': [{'line_number': 14,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: os'},
  {'line_number': 15,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: sys'},
  {'line_number': 16,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: re'},
  {'line_number': 18,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: Optional'}],
 'synthetic-django_PR_32': [{'line_number': 17,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: createUser'},
  {'line_number': 19,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: _createUser'},
  {'line_number': 37,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: createCategory'},
  {'line_number': 39,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: _createCategory'},
  {'line_number': 51,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase parameter: createUser'},
  {'line_number': 51,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase parameter: createCategory'}],
 'synthetic-django_PR_33': [{'line_number': 3,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: os'},
  {'line_number': 4,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: sys'},
  {'line_number': 5,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: re'},
  {'line_number': 13,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (2 spaces)'},
  {'line_number': 26,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (4 spaces)'},
  {'line_number': 40,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (6 spaces)'},
  {'line_number': 13,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"}],
 'synthetic-django_PR_34': [{'line_number': 19,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase parameter: testData'},
  {'line_number': 28,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: testArticleCreation'},
  {'line_number': 36,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase parameter: expectedSlugs'},
  {'line_number': 41,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: testCategoryRelationship'},
  {'line_number': 50,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase parameter: initialData'},
  {'line_number': 19,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default [] for param 'testData'"},
  {'line_number': 36,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default {} for param 'expectedSlugs'"},
  {'line_number': 50,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default [] for param 'initialData'"}],
 'synthetic-django_PR_35': [{'line_number': 1,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: os'},
  {'line_number': 2,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: sys'},
  {'line_number': 3,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: re'},
  {'line_number': 4,
   'violation_category': 'documentation_formatting',
   'review_comment': 'Module docstring placed after imports'}],
 'synthetic-django_PR_36': [{'line_number': 16,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase variable: urlPatterns'}],
 'synthetic-django_PR_37': [{'line_number': 10,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: random'},
  {'line_number': 11,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: string'},
  {'line_number': 48,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default [] for param 'subject'"}],
 'synthetic-django_PR_38': [{'line_number': 9,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: os'},
  {'line_number': 10,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: sys'},
  {'line_number': 36,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default [] for param 'slug'"},
  {'line_number': 55,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default {'badword1', 'badword2', 'badword3'} for param 'value'"}],
 'synthetic-django_PR_39': [{'line_number': 9,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: os'},
  {'line_number': 10,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: sys'},
  {'line_number': 11,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: re'},
  {'line_number': 17,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: FormMixin'},
  {'line_number': 68,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: formValid'},
  {'line_number': 23,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (2 spaces)'},
  {'line_number': 32,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (4 spaces)'},
  {'line_number': 39,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (2 spaces)'},
  {'line_number': 47,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (4 spaces)'},
  {'line_number': 58,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (2 spaces)'},
  {'line_number': 69,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (4 spaces)'},
  {'line_number': 23,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 25,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 32,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 34,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 39,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 41,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 47,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 49,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 58,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 69,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 71,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"}],
 'synthetic-django_PR_40': [{'line_number': 22,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: configureEnvironment'},
  {'line_number': 41,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: anotherFunction'},
  {'line_number': 45,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: yetAnotherFunction'},
  {'line_number': 41,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default [] for param 'my_list'"},
  {'line_number': 45,
   'violation_category': 'mutable_default',
   'review_comment': "Mutable default {} for param 'my_dict'"}],
 'synthetic-fastapi_PR_21': [{'line_number': 8,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: os'},
  {'line_number': 9,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: sys'},
  {'line_number': 10,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: re'}],
 'synthetic-fastapi_PR_22': [{'line_number': 11,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: NoResultFound'},
  {'line_number': 17,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: getItem'},
  {'line_number': 35,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: getItems'},
  {'line_number': 59,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: createItem'},
  {'line_number': 78,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: updateItem'}],
 'synthetic-fastapi_PR_23': [{'line_number': 8,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: os'},
  {'line_number': 9,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: sys'},
  {'line_number': 10,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: re'},
  {'line_number': 16,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: NoResultFound'},
  {'line_number': 23,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (2 spaces)'},
  {'line_number': 39,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (2 spaces)'},
  {'line_number': 58,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (2 spaces)'},
  {'line_number': 76,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (2 spaces)'},
  {'line_number': 90,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (4 spaces)'},
  {'line_number': 92,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (4 spaces)'},
  {'line_number': 99,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (2 spaces)'},
  {'line_number': 112,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (4 spaces)'},
  {'line_number': 23,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 39,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 58,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 76,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"},
  {'line_number': 99,
   'violation_category': 'documentation_formatting',
   'review_comment': "Docstring indentation doesn't match block"}],
 'synthetic-fastapi_PR_24': [{'line_number': 14,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: Depends'},
  {'line_number': 38,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: getDb'}],
 'synthetic-fastapi_PR_25': [{'line_number': 11,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: Optional'},
  {'line_number': 13,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: os'},
  {'line_number': 14,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: sys'},
  {'line_number': 15,
   'violation_category': 'unused_import',
   'review_comment': 'Unused import: re'}],
 'synthetic-fastapi_PR_26': [{'line_number': 49,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: notFoundErrorHandler'},
  {'line_number': 64,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: forbiddenErrorHandler'},
  {'line_number': 79,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: validationErrorHandler'},
  {'line_number': 97,
   'violation_category': 'naming_convention',
   'review_comment': 'camelCase function name: registerExceptionHandlers'},
  {'line_number': 19,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (2 spaces)'},
  {'line_number': 24,
   'violation_category': 'indentation',
   'review_comment': 'Non-4-space indent (4 spaces)'},
  {'line_number': 29,

In [28]:
# Group retrieved chunks per PR id and print ground-truth and retrieved chunks
# Load ground-truth list from evaluation.json if available
try:
    with open(EVAL_PATH, 'r', encoding='utf-8') as f:
        full_eval = json.load(f)
    gt_map_list = {e.get('id'): e.get('ground_truth_reviews') for e in full_eval}
except Exception:
    gt_map_list = {e.get('id'): e.get('ground_truth_reviews') for e in sampled_entries}

# Build grouped metadata for iteration
grouped = (
    results_df.groupby('id')
    .agg(
        repo=('repo', 'first'),
        resolved_source_file=('resolved_source_file', 'first'),
        retrieved_count=('retrieved_count', 'first')
    )
    .reset_index()
)

# Iterate and print as requested
for _, row in grouped.iterrows():
    pid = row['id']
    print(f"ID: {pid} | repo: {row['repo']} | resolved: {row['resolved_source_file']}")

    # Ground-truth reviews
    gt_list = gt_map_list.get(pid)
    if gt_list:
        for gt in gt_list:
            ln = gt.get('line_number') if isinstance(gt, dict) else None
            cat = gt.get('violation_category') if isinstance(gt, dict) else None
            comment = gt.get('review_comment') if isinstance(gt, dict) else str(gt)
            print(f"  GT: ({ln}, {cat}, {comment})")
    else:
        print("  GT: None")

    # Retrieved chunks for this PR
    rows_for_id = results_df[results_df['id'] == pid]
    if not rows_for_id.empty:
        for _, r in rows_for_id.iterrows():
            idx = r.get('chunk_index')
            tt = r.get('time_taken')
            payload = r.get('retrieved_payload')
            print(f"  Retrieved: (chunk_index={idx}, time_taken={tt}, payload={payload})")
    else:
        print("  Retrieved: None")

    print("---")

ID: synthetic-django_PR_24 | repo: kannan-dedsec/synthetic-django | resolved: C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1-DS-and-AI-Lab-Project\data\processed\evaluation_files\synthetic-django_PR_24_managers.py
  GT: (32, naming_convention, camelCase function name: byAuthor)
  GT: (42, naming_convention, camelCase function name: withinDateRange)
  GT: (83, naming_convention, camelCase function name: byAuthor)
  GT: (93, naming_convention, camelCase function name: withinDateRange)
  GT: (32, mutable_default, Mutable default [] for param 'author_id')
  GT: (42, mutable_default, Mutable default [] for param 'start_date')
  GT: (42, mutable_default, Mutable default {} for param 'end_date')
  GT: (83, mutable_default, Mutable default [] for param 'author_id')
  GT: (93, mutable_default, Mutable default [] for param 'start_date')
  GT: (93, mutable_default, Mutable default {} for param 'end_date')
  Retrieved: (chunk_index=0, time_taken=0.5805328100046608, payload={'text': "The indentation in the `markdown_to_html` function docstring deviates from the project's 4-space standard. Please adjust it to maintain consistency with the rest of the codebase.", 'category': 'indentation', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0222'})
  Retrieved: (chunk_index=1, time_taken=0.5805328100046608, payload={'text': 'W0404 (reimported): A module is imported more than once. Remove the duplicate import statement.', 'category': 'unused_import', 'source_type': 'pylint', 'chunk_id': 'chunk_0073'})
  Retrieved: (chunk_index=2, time_taken=0.5805328100046608, payload={'text': 'The project repository includes an .editorconfig file. We recommend using a text editor with EditorConfig support to avoid indentation and whitespace issues.', 'category': 'documentation_formatting', 'source_type': 'django_guidelines', 'chunk_id': 'chunk_0130'})
  Retrieved: (chunk_index=3, time_taken=0.5805328100046608, payload={'text': 'N813: CamelCase imported as lowercase. Preserve CamelCase when importing class names.', 'category': 'naming_convention', 'source_type': 'ruff', 'chunk_id': 'chunk_0054'})
  Retrieved: (chunk_index=4, time_taken=0.5805328100046608, payload={'text': 'N814: CamelCase imported as constant. Do not alias CamelCase imports to UPPER_CASE names.', 'category': 'naming_convention', 'source_type': 'ruff', 'chunk_id': 'chunk_0055'})
  Retrieved: (chunk_index=5, time_taken=0.5805328100046608, payload={'text': "It looks like there's a mix of tabs and spaces in the `create_category` function. For consistency and to avoid potential issues, please standardize the indentation to use either tabs or spaces throughout the fileâ€”spaces are generally preferred in Python projects.", 'category': 'indentation', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0243'})
  Retrieved: (chunk_index=6, time_taken=0.5805328100046608, payload={'text': 'It looks like the indentation for the `clean_title` method has changed from 4 spaces to 6 spaces, which can affect code readability and consistency. Please revert it back to 4 spaces to maintain uniformity with the rest of the codebase.', 'category': 'indentation', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0230'})
  Retrieved: (chunk_index=7, time_taken=0.5805328100046608, payload={'text': 'N817: CamelCase imported as acronym. Do not alias CamelCase imports to ALL_CAPS acronyms.', 'category': 'naming_convention', 'source_type': 'ruff', 'chunk_id': 'chunk_0058'})
  Retrieved: (chunk_index=8, time_taken=0.5805328100046608, payload={'text': 'Please replace the tabs with spaces in the `handle_article_tags_change` function to maintain consistent indentation throughout the file. This will help improve code readability and prevent potential issues in the future.', 'category': 'indentation', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0255'})
  Retrieved: (chunk_index=9, time_taken=0.5805328100046608, payload={'text': 'The indentation for the parameters in the `create_category` function is inconsistent; please align them to 4 spaces to maintain uniformity with the rest of the code.', 'category': 'indentation', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0244'})
---
ID: synthetic-django_PR_35 | repo: kannan-dedsec/synthetic-django | resolved: C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1-DS-and-AI-Lab-Project\data\processed\evaluation_files\synthetic-django_PR_35_tests_test_views.py
  GT: (1, unused_import, Unused import: os)
  GT: (2, unused_import, Unused import: sys)
  GT: (3, unused_import, Unused import: re)
  GT: (4, documentation_formatting, Module docstring placed after imports)
  Retrieved: (chunk_index=0, time_taken=0.6168301800033078, payload={'text': 'W0404 (reimported): A module is imported more than once. Remove the duplicate import statement.', 'category': 'unused_import', 'source_type': 'pylint', 'chunk_id': 'chunk_0073'})
  Retrieved: (chunk_index=1, time_taken=0.6168301800033078, payload={'text': 'N814: CamelCase imported as constant. Do not alias CamelCase imports to UPPER_CASE names.', 'category': 'naming_convention', 'source_type': 'ruff', 'chunk_id': 'chunk_0055'})
  Retrieved: (chunk_index=2, time_taken=0.6168301800033078, payload={'text': 'N813: CamelCase imported as lowercase. Preserve CamelCase when importing class names.', 'category': 'naming_convention', 'source_type': 'ruff', 'chunk_id': 'chunk_0054'})
  Retrieved: (chunk_index=3, time_taken=0.6168301800033078, payload={'text': "The indentation in the `markdown_to_html` function docstring deviates from the project's 4-space standard. Please adjust it to maintain consistency with the rest of the codebase.", 'category': 'indentation', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0222'})
  Retrieved: (chunk_index=4, time_taken=0.6168301800033078, payload={'text': 'N817: CamelCase imported as acronym. Do not alias CamelCase imports to ALL_CAPS acronyms.', 'category': 'naming_convention', 'source_type': 'ruff', 'chunk_id': 'chunk_0058'})
  Retrieved: (chunk_index=5, time_taken=0.6168301800033078, payload={'text': "Let's stick with the PEP 8 style guide, which recommends using snake_case for function names in Python. Please rename `testCategoryCreation` back to `test_category_creation` for better consistency and readability.", 'category': 'naming_convention', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0258'})
  Retrieved: (chunk_index=6, time_taken=0.6168301800033078, payload={'text': 'The project repository includes an .editorconfig file. We recommend using a text editor with EditorConfig support to avoid indentation and whitespace issues.', 'category': 'documentation_formatting', 'source_type': 'django_guidelines', 'chunk_id': 'chunk_0130'})
  Retrieved: (chunk_index=7, time_taken=0.6168301800033078, payload={'text': "It looks like there's a mix of tabs and spaces in the `create_category` function. For consistency and to avoid potential issues, please standardize the indentation to use either tabs or spaces throughout the fileâ€”spaces are generally preferred in Python projects.", 'category': 'indentation', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0243'})
  Retrieved: (chunk_index=8, time_taken=0.6168301800033078, payload={'text': 'Use absolute imports for other Django components and a one-dot relative import for local components. Avoid multi-dot relative imports.', 'category': 'unused_import', 'source_type': 'django_guidelines', 'chunk_id': 'chunk_0147'})
  Retrieved: (chunk_index=9, time_taken=0.6168301800033078, payload={'text': 'Python packages should have short, all-lowercase names. The use of underscores is discouraged in package names.', 'category': 'naming_convention', 'source_type': 'pep8', 'chunk_id': 'chunk_0035'})
---
ID: synthetic-django_PR_36 | repo: kannan-dedsec/synthetic-django | resolved: C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1-DS-and-AI-Lab-Project\data\processed\evaluation_files\synthetic-django_PR_36_urls.py
  GT: (16, naming_convention, camelCase variable: urlPatterns)
  Retrieved: (chunk_index=0, time_taken=0.5730826399987563, payload={'text': "The indentation in the `markdown_to_html` function docstring deviates from the project's 4-space standard. Please adjust it to maintain consistency with the rest of the codebase.", 'category': 'indentation', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0222'})
  Retrieved: (chunk_index=1, time_taken=0.5730826399987563, payload={'text': 'W0404 (reimported): A module is imported more than once. Remove the duplicate import statement.', 'category': 'unused_import', 'source_type': 'pylint', 'chunk_id': 'chunk_0073'})
  Retrieved: (chunk_index=2, time_taken=0.5730826399987563, payload={'text': 'The project repository includes an .editorconfig file. We recommend using a text editor with EditorConfig support to avoid indentation and whitespace issues.', 'category': 'documentation_formatting', 'source_type': 'django_guidelines', 'chunk_id': 'chunk_0130'})
  Retrieved: (chunk_index=3, time_taken=0.5730826399987563, payload={'text': 'N814: CamelCase imported as constant. Do not alias CamelCase imports to UPPER_CASE names.', 'category': 'naming_convention', 'source_type': 'ruff', 'chunk_id': 'chunk_0055'})
  Retrieved: (chunk_index=4, time_taken=0.5730826399987563, payload={'text': 'N813: CamelCase imported as lowercase. Preserve CamelCase when importing class names.', 'category': 'naming_convention', 'source_type': 'ruff', 'chunk_id': 'chunk_0054'})
  Retrieved: (chunk_index=5, time_taken=0.5730826399987563, payload={'text': 'Use absolute imports for other Django components and a one-dot relative import for local components. Avoid multi-dot relative imports.', 'category': 'unused_import', 'source_type': 'django_guidelines', 'chunk_id': 'chunk_0147'})
  Retrieved: (chunk_index=6, time_taken=0.5730826399987563, payload={'text': "It looks like there's a mix of tabs and spaces in the `create_category` function. For consistency and to avoid potential issues, please standardize the indentation to use either tabs or spaces throughout the fileâ€”spaces are generally preferred in Python projects.", 'category': 'indentation', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0243'})
  Retrieved: (chunk_index=7, time_taken=0.5730826399987563, payload={'text': 'It looks like the import statement for `json` on line 3 is not being used anywhere in the file. Consider removing it to keep the code clean and improve readability.', 'category': 'unused_import', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0253'})
  Retrieved: (chunk_index=8, time_taken=0.5730826399987563, payload={'text': 'N817: CamelCase imported as acronym. Do not alias CamelCase imports to ALL_CAPS acronyms.', 'category': 'naming_convention', 'source_type': 'ruff', 'chunk_id': 'chunk_0058'})
  Retrieved: (chunk_index=9, time_taken=0.5730826399987563, payload={'text': 'It looks like the indentation for the `clean_title` method has changed from 4 spaces to 6 spaces, which can affect code readability and consistency. Please revert it back to 4 spaces to maintain uniformity with the rest of the codebase.', 'category': 'indentation', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0230'})
---
ID: synthetic-django_PR_39 | repo: kannan-dedsec/synthetic-django | resolved: C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1-DS-and-AI-Lab-Project\data\processed\evaluation_files\synthetic-django_PR_39_views.py
  GT: (9, unused_import, Unused import: os)
  GT: (10, unused_import, Unused import: sys)
  GT: (11, unused_import, Unused import: re)
  GT: (17, unused_import, Unused import: FormMixin)
  GT: (68, naming_convention, camelCase function name: formValid)
  GT: (23, indentation, Non-4-space indent (2 spaces))
  GT: (32, indentation, Non-4-space indent (4 spaces))
  GT: (39, indentation, Non-4-space indent (2 spaces))
  GT: (47, indentation, Non-4-space indent (4 spaces))
  GT: (58, indentation, Non-4-space indent (2 spaces))
  GT: (69, indentation, Non-4-space indent (4 spaces))
  GT: (23, documentation_formatting, Docstring indentation doesn't match block)
  GT: (25, documentation_formatting, Docstring indentation doesn't match block)
  GT: (32, documentation_formatting, Docstring indentation doesn't match block)
  GT: (34, documentation_formatting, Docstring indentation doesn't match block)
  GT: (39, documentation_formatting, Docstring indentation doesn't match block)
  GT: (41, documentation_formatting, Docstring indentation doesn't match block)
  GT: (47, documentation_formatting, Docstring indentation doesn't match block)
  GT: (49, documentation_formatting, Docstring indentation doesn't match block)
  GT: (58, documentation_formatting, Docstring indentation doesn't match block)
  GT: (69, documentation_formatting, Docstring indentation doesn't match block)
  GT: (71, documentation_formatting, Docstring indentation doesn't match block)
  Retrieved: (chunk_index=0, time_taken=0.6036573299963492, payload={'text': "The indentation in the `markdown_to_html` function docstring deviates from the project's 4-space standard. Please adjust it to maintain consistency with the rest of the codebase.", 'category': 'indentation', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0222'})
  Retrieved: (chunk_index=1, time_taken=0.6036573299963492, payload={'text': 'N813: CamelCase imported as lowercase. Preserve CamelCase when importing class names.', 'category': 'naming_convention', 'source_type': 'ruff', 'chunk_id': 'chunk_0054'})
  Retrieved: (chunk_index=2, time_taken=0.6036573299963492, payload={'text': 'The project repository includes an .editorconfig file. We recommend using a text editor with EditorConfig support to avoid indentation and whitespace issues.', 'category': 'documentation_formatting', 'source_type': 'django_guidelines', 'chunk_id': 'chunk_0130'})
  Retrieved: (chunk_index=3, time_taken=0.6036573299963492, payload={'text': 'N814: CamelCase imported as constant. Do not alias CamelCase imports to UPPER_CASE names.', 'category': 'naming_convention', 'source_type': 'ruff', 'chunk_id': 'chunk_0055'})
  Retrieved: (chunk_index=4, time_taken=0.6036573299963492, payload={'text': 'W0404 (reimported): A module is imported more than once. Remove the duplicate import statement.', 'category': 'unused_import', 'source_type': 'pylint', 'chunk_id': 'chunk_0073'})
  Retrieved: (chunk_index=5, time_taken=0.6036573299963492, payload={'text': 'It looks like the indentation in the `ArticleForm` class is inconsistent with the rest of the file; please ensure it uses 4 spaces to maintain uniformity across the codebase.', 'category': 'indentation', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0231'})
  Retrieved: (chunk_index=6, time_taken=0.6036573299963492, payload={'text': 'It looks like the docstring was removed from the `test_valid_form` function. Please consider adding it back to maintain clarity about the purpose of the test and to follow our documentation standards.', 'category': 'documentation_formatting', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0261'})
  Retrieved: (chunk_index=7, time_taken=0.6036573299963492, payload={'text': "It looks like there's a mix of tabs and spaces in the `create_category` function. For consistency and to avoid potential issues, please standardize the indentation to use either tabs or spaces throughout the fileâ€”spaces are generally preferred in Python projects.", 'category': 'indentation', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0243'})
  Retrieved: (chunk_index=8, time_taken=0.6036573299963492, payload={'text': "The docstring for `test_empty_form` should remain concise and informative; let's convert it back to a single line or ensure it's properly formatted if it needs to be multi-line. This will improve readability and maintain consistency with the rest of the test cases.", 'category': 'documentation_formatting', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0262'})
  Retrieved: (chunk_index=9, time_taken=0.6036573299963492, payload={'text': 'It looks like the indentation for the `clean_title` method has changed from 4 spaces to 6 spaces, which can affect code readability and consistency. Please revert it back to 4 spaces to maintain uniformity with the rest of the codebase.', 'category': 'indentation', 'source_type': 'django_review_comment', 'chunk_id': 'chunk_0230'})
---
ID: synthetic-fastapi_PR_31 | repo: kannan-dedsec/synthetic-fastapi | resolved: C:\Users\budhi\Documents\IITM\DSAI Lab\Group-1-DS-and-AI-Lab-Project\data\processed\evaluation_files\synthetic-fastapi_PR_31_routers_auth.py
  GT: (10, unused_import, Unused import: os)
  GT: (11, unused_import, Unused import: sys)
  GT: (12, unused_import, Unused import: re)
  GT: (14, unused_import, Unused import: Request)
  Retrieved: (chunk_index=0, time_taken=0.5817285199998878, payload={'text': 'N814: CamelCase imported as constant. Do not alias CamelCase imports to UPPER_CASE names.', 'category': 'naming_convention', 'source_type': 'ruff', 'chunk_id': 'chunk_0055'})
  Retrieved: (chunk_index=1, time_taken=0.5817285199998878, payload={'text': 'W0404 (reimported): A module is imported more than once. Remove the duplicate import statement.', 'category': 'unused_import', 'source_type': 'pylint', 'chunk_id': 'chunk_0073'})
  Retrieved: (chunk_index=2, time_taken=0.5817285199998878, payload={'text': 'N817: CamelCase imported as acronym. Do not alias CamelCase imports to ALL_CAPS acronyms.', 'category': 'naming_convention', 'source_type': 'ruff', 'chunk_id': 'chunk_0058'})
  Retrieved: (chunk_index=3, time_taken=0.5817285199998878, payload={'text': "Noticed the TokenResponse class is using 2-space indentation instead of the project's standard 4 spacesâ€”let's keep it consistent to avoid confusion and maintain readability.", 'category': 'indentation', 'source_type': 'fastapi_review_comment', 'chunk_id': 'chunk_0271'})
  Retrieved: (chunk_index=4, time_taken=0.5817285199998878, payload={'text': 'It looks like the indentation for the `RequestTimingMiddleware` class is inconsistent with the rest of the file, switching from 4 spaces to 2 spaces. Please adjust the indentation to maintain uniformity throughout the codebase.', 'category': 'indentation', 'source_type': 'fastapi_review_comment', 'chunk_id': 'chunk_0297'})
  Retrieved: (chunk_index=5, time_taken=0.5817285199998878, payload={'text': "It's great to see your work on the API, but could we stick to the PEP 8 naming conventions for function names? Let's rename `createItem` back to `create_item` to maintain consistency and readability in our codebase.", 'category': 'naming_convention', 'source_type': 'fastapi_review_comment', 'chunk_id': 'chunk_0290'})
  Retrieved: (chunk_index=6, time_taken=0.5817285199998878, payload={'text': 'The indentation for the docstring at line 41 appears to be inconsistent with the rest of the class; please adjust it back to 4 spaces for readability and to maintain our coding standards.', 'category': 'indentation', 'source_type': 'fastapi_review_comment', 'chunk_id': 'chunk_0287'})
  Retrieved: (chunk_index=7, time_taken=0.5817285199998878, payload={'text': 'The indentation for the `RequestTimingMiddleware` class is inconsistent with the rest of the file; please revert it to 4 spaces to maintain uniformity and improve readability.', 'category': 'indentation', 'source_type': 'fastapi_review_comment', 'chunk_id': 'chunk_0286'})
  Retrieved: (chunk_index=8, time_taken=0.5817285199998878, payload={'text': 'N813: CamelCase imported as lowercase. Preserve CamelCase when importing class names.', 'category': 'naming_convention', 'source_type': 'ruff', 'chunk_id': 'chunk_0054'})

In [12]:
results_df["query"].value_counts()

query
repo family: scikit-learn ; import statements count: 4 ; camelCase identifiers: filteredData, fitTransform, lowerBound, upperBound ; mutable-default patterns: 2 ; indentation issues: 0 ; docstring markers count: 12 ; focus on naming_convention, unused_import, indentation, mutable_default, documentation_formatting                                       10
repo family: django ; import statements count: 2 ; camelCase identifiers: urlPatterns ; mutable-default patterns: 0 ; indentation issues: 6 ; docstring markers count: 2 ; focus on naming_convention, unused_import, indentation, mutable_default, documentation_formatting                                                                                     10
repo family: django ; import statements count: 2 ; camelCase identifiers: byAuthor, withinDateRange ; mutable-default patterns: 4 ; indentation issues: 0 ; docstring markers count: 24 ; focus on naming_convention, unused_import, indentation, mutable_default, documentation_formatting                                                                      10
repo family: scikit-learn ; import statements count: 12 ; camelCase identifiers: none ; mutable-default patterns: 3 ; indentation issues: 0 ; docstring markers count: 14 ; focus on naming_convention, unused_import, indentation, mutable_default, documentation_formatting                                                                                    10
repo family: fastapi ; import statements count: 7 ; camelCase identifiers: none ; mutable-default patterns: 0 ; indentation issues: 0 ; docstring markers count: 18 ; focus on naming_convention, unused_import, indentation, mutable_default, documentation_formatting                                                                                          10
repo family: fastapi ; import statements count: 3 ; camelCase identifiers: nameNotBlank, priceTwoDecimals ; mutable-default patterns: 0 ; indentation issues: 0 ; docstring markers count: 10 ; focus on naming_convention, unused_import, indentation, mutable_default, documentation_formatting                                                                10
repo family: fastapi ; import statements count: 12 ; camelCase identifiers: tokenUrl ; mutable-default patterns: 0 ; indentation issues: 0 ; docstring markers count: 10 ; focus on naming_convention, unused_import, indentation, mutable_default, documentation_formatting                                                                                     10
repo family: django ; import statements count: 11 ; camelCase identifiers: formValid ; mutable-default patterns: 0 ; indentation issues: 25 ; docstring markers count: 14 ; focus on naming_convention, unused_import, indentation, mutable_default, documentation_formatting                                                                                    10
repo family: django ; import statements count: 7 ; camelCase identifiers: assertContains, assertEqual, assertNotEqual, assertTrue, setUp ; mutable-default patterns: 0 ; indentation issues: 0 ; docstring markers count: 12 ; focus on naming_convention, unused_import, indentation, mutable_default, documentation_formatting                                 10
repo family: scikit-learn ; import statements count: 4 ; camelCase identifiers: bayesianOptimizationTuning, getDefaultParamGrids, gridSearchTuning, randomSearchTuning ; mutable-default patterns: 2 ; indentation issues: 6 ; docstring markers count: 8 ; focus on naming_convention, unused_import, indentation, mutable_default, documentation_formatting    10
Name: count, dtype: int64

In [ ]:
results_df